---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    Vulnerable swagger UI <a href="https://evil.com">link</a>

  version: production
basePath: https://target.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/testt":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - Test
      operationId: findAccounts
      summary: this is example text
  "/exploited_by_ValueMentor":
    delete:
      parameters:
      - description: |
          <a href=https://valuementor.com>blog</a>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: swagger
      summary: swagger
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
